package com.ccb.dianping.dal;

import com.ccb.dianping.model.bean.Category;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int updateByPrimaryKey(Category record);

    @Select("select * from dianping_db.`category` order by sort DESC,id ASC limit #{pageStart},#{pageSize}")
    List<Category> selectPage(@Param("pageStart") Integer pageStart
            , @Param("pageSize") Integer pageSize);

    @Select("select count(*) from dianping_db.`category`")
    Long categoryCount();
}