package com.ccb.dianping.dal;

import com.ccb.dianping.model.bean.Seller;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int insert(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int insertSelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    Seller selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int updateByPrimaryKeySelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int updateByPrimaryKey(Seller record);

    @Select("select count(*) from dianping_db.`seller`")
    long sellerCount();

    @Select("select * from dianping_db.`seller` limit #{pageStart},#{pageSize}")
    List<Seller> selectPage(@Param("pageStart") Integer pageStart
            , @Param("pageSize") Integer pageSize);
}