package com.ccb.dianping.dal;

import com.ccb.dianping.model.bean.Shop;
import org.apache.ibatis.annotations.Select;

import java.util.List;


public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    Shop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Jan 27 11:47:50 CST 2020
     */
    int updateByPrimaryKey(Shop record);

    @Select("select count(*) from dianping_db.`shop`")
    Long shopCount();

    @Select("select * from dianping_db.`shop` limit #{pageStart},#{pageSize}")
    List<Shop> selectPage(Integer pageStart, Integer pageSize);
}