server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapping/*.xml
  #别名包
  type-aliases-package: com.ccb.dianping.model.bean
  configuration:
    #匹配驼峰规则
    map-underscore-to-camel-case: true
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/dianping_db?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    #add-mappings=true表示如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配
    add-mappings: true
  mvc:
    #接入前端静态资源页面，访问以下形式的路径时按静态资源处理
    static-path-pattern: /static/**
    #请求路径没有命中时抛出异常
    throw-exception-if-no-handler-found: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
admin:
    email: 2568808909@qq.com
    encryptPassword: 4QrcOUm6Wau+VuBX8g+IPg==

